[tool.ruff]
line-length = 88  # Совпадает со значением по умолчанию в Black
lint.ignore = ["E203", "E266", "E501", "D103","D100", "D101", "ANN003", "D104", "ANN201", "ANN001", "D107", "D106", "B904","D102"]
lint.select = ["E", "F", "W", "B", "C", "N", "Q", "ANN", "D"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]  # Игнорировать F401 в __init__.py
